### ISSUE TITLE
Sidebar: "Open media picker" tooltip is hidden behind WP admin menu

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11041]
## Bug Description
Originally reported by @BrookeGraham 

Could be fixed by Popup separation. Found in Firefox
<img width="185" alt="image4" src="https://user-images.githubusercontent.com/58738530/159690964-35436a67-773c-4109-9056-088b2032cdea.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrookeGraham** [comment]
Hi @merapi I was able to fix this with #11280

**Comment by merapi** [comment]
> Hi @merapi I was able to fix this with #11280

Alright, although I see that is already fixed on main (ordering)?
Firefox:
![image](https://user-images.githubusercontent.com/21036224/164205578-63a69fe9-4598-4890-9d55-7bba9b3b3e73.png)

**Comment by BrookeGraham** [comment]
It isn't really fixed on main yet. The issue is more apparent if you collapse the Visibility panel. The tooltip is still rendering below the admin side nav, it is just that the admin side bar nav stops before your screenshot.
![Kapture 2022-04-20 at 04 49 06](https://user-images.githubusercontent.com/1820266/164215667-c09f86e6-25b9-4d9c-a7ff-831c03189ab6.gif)

**Comment by BrookeGraham** [comment]
@felipebochehin87 you can use #11280 to check this.
